version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly" # Can be "daily", "weekly", or "monthly"
    commit-message:
      prefix: "dependabot-fix" # You can customize this prefix
    versioning-strategy: "auto"
